### PR TITLE
add more failsafe lookup call as workaround to random "Backend Error"

### PR DESCRIPTION
**Pull request by neonknight**
works around errors as described in https://github.com/afilipovich/gglsbl/issues/27

### CODE REVIEW

**Comment by asieira** [comment]
Thank you for submitting this, I ended up implementing similar functionality in https://github.com/mlsecproject/gglsbl-rest/pull/5 so I will close this. Let me know if this works for you.

**Comment by neonknight** [comment]
Thank you for handling this, I updated the code and will keep an eye on logs.

**Comment by asieira** [comment]
Awesome, let me know how it goes. 

Also, keep in mind we have automated builds on Docker Hub, which might make your deployment a bit easier: https://hub.docker.com/r/mlsecproject/gglsbl-rest/

**Comment by asieira** [comment]
By the way, @neonknight, I wanted to add a section to README.md indicating which projects and/or companies are currently using gglsbl-rest. If you could provide more details on what you are using it for and allow me to publish data, I'd be delighted.

**Comment by neonknight** [comment]
We use gglsbl-rest as bridge between our fuglu mail filter engine (https://github.com/gryphius/fuglu) and google safebrowsing api (using https://github.com/gryphius/fuglu-extra-plugins/blob/master/safebrowsing/gglsbl.py)

**Comment by asieira** [comment]
Just added a mention in README.md, thank you! 🙇

**Pull request closed without merging**
